const KEY='fariMoneyAssistant_v1';
const defaultState={income:{fixed:0,side:0,trading:0,other:0,essential:0,buffer:0},transactions:[],debts:[],goals:[],credits:[]};
let state=load();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>`AED ${Number(n||0).toLocaleString('en-AE',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function daysUntil(date){return Math.ceil((new Date(date+'T23:59:59')-new Date())/86400000)}
function monthsUntil(date){const d=new Date(date+'T12:00:00'), n=new Date();return Math.max(1,(d.getFullYear()-n.getFullYear())*12+d.getMonth()-n.getMonth()+1)}
function totalIncome(){const i=state.income;return +i.fixed + +i.side + +i.trading + +i.other}
function monthTxn(type){const now=new Date();return state.transactions.filter(t=>t.type===type&&new Date(t.date).getMonth()===now.getMonth()&&new Date(t.date).getFullYear()===now.getFullYear()).reduce((s,t)=>s+Number(t.amount),0)}
function debtPriorityScore(d){let s=d.fixed?100:0;if(d.interest&&d.rate>0)s+=35;if(d.priority==='critical')s+=40;if(d.priority==='high')s+=25;if(d.type==='Credit Card')s+=20;return s}
function buildPlan(){
 const income=totalIncome()+monthTxn('Income');
 const fixedDebts=state.debts.filter(d=>d.fixed).reduce((s,d)=>s+Math.min(+d.monthly,+d.balance),0);
 const creditFees=state.credits.reduce((s,c)=>s+Number(c.fee||0),0);
 const mandatory=fixedDebts+creditFees;
 const essential=Number(state.income.essential||0);
 const buffer=Number(state.income.buffer||0);
 let remaining=income-mandatory-essential-buffer;
 const allocations=[];
 state.debts.filter(d=>d.fixed).sort((a,b)=>debtPriorityScore(b)-debtPriorityScore(a)).forEach(d=>allocations.push({type:'Fixed debt',name:d.name,amount:Math.min(+d.monthly,+d.balance),priority:'Mandatory'}));
 if(essential>0) allocations.push({type:'Living',name:'Essential living budget',amount:essential,priority:'Mandatory'});
 const goalPlans=state.goals.map(g=>{const need=Math.max(0,+g.amount-+g.saved);const m=monthsUntil(g.deadline);return {...g,need,monthly:need/m}}).sort((a,b)=>(a.priority==='critical'?-2:a.priority==='high'?-1:0)-(b.priority==='critical'?-2:b.priority==='high'?-1:0)||new Date(a.deadline)-new Date(b.deadline));
 for(const g of goalPlans){if(remaining<=0)break;const amt=Math.min(g.monthly,remaining);allocations.push({type:'Urgent goal',name:g.name,amount:amt,priority:g.priority});remaining-=amt}
 const flex=state.debts.filter(d=>!d.fixed).sort((a,b)=>debtPriorityScore(b)-debtPriorityScore(a));
 for(const d of flex){if(remaining<=0)break;let desired=Math.min(+d.monthly||0,+d.balance);let min=Math.min(+d.minimum||0,+d.balance);let amt=remaining>=desired?desired:Math.min(remaining,Math.max(min,remaining*.45));amt=Math.max(0,amt);if(amt){allocations.push({type:'Flexible debt',name:d.name,amount:amt,priority:d.priority});remaining-=amt}}
 if(buffer>0) allocations.push({type:'Buffer',name:'Emergency buffer',amount:buffer,priority:'Protected'});
 const free=Math.max(0,remaining);
 const shortfall=Math.max(0,-(income-mandatory-essential-buffer));
 return {income,mandatory,essential,buffer,allocations,free,shortfall,goalPlans};
}
function renderDashboard(){const p=buildPlan();const debt=state.debts.reduce((s,d)=>s+Number(d.balance),0)+state.credits.reduce((s,c)=>s+Number(c.balance),0);const goalNeed=state.goals.reduce((s,g)=>s+Math.max(0,+g.amount-+g.saved),0);$('#safeToSpend').textContent=money(p.free);$('#statIncome').textContent=money(p.income);$('#statMandatory').textContent=money(p.mandatory+p.essential);$('#statDebt').textContent=money(debt);$('#statGoals').textContent=money(goalNeed);let health='GOOD',msg='Your protected commitments are covered and you still have flexible money available.';if(p.income===0){health='SETUP';msg='Add your income and commitments to generate your plan.'}else if(p.shortfall>0){health='CRITICAL';msg=`Your protected commitments exceed available income by ${money(p.shortfall)}.`}else if(p.free<Math.max(200,p.income*.05)){health='TIGHT';msg='Your month is very tight. Avoid optional spending and protect upcoming payments.'}$('#healthBadge').textContent=health;$('#heroMessage').textContent=msg;
 const priority=p.allocations.slice(0,6);$('#priorityList').innerHTML=priority.length?priority.map((x,i)=>`<div class="priority-item"><div class="priority-rank">${i+1}</div><div class="item-main"><strong>${x.name}</strong><small>${x.type} • ${x.priority}</small></div><div class="item-amount">${money(x.amount)}</div></div>`).join(''):'No priorities yet.';
 const upcoming=[...state.debts.filter(d=>d.fixed).map(d=>({name:d.name,amount:Math.min(+d.monthly,+d.balance),days:(+d.dueDay-new Date().getDate()+31)%31})),...state.goals.map(g=>({name:g.name,amount:Math.max(0,+g.amount-+g.saved),days:daysUntil(g.deadline)}))].sort((a,b)=>a.days-b.days).slice(0,5);$('#upcomingList').innerHTML=upcoming.length?upcoming.map(x=>`<div class="timeline-item"><div class="item-main"><strong>${x.name}</strong><small>${x.days<=0?'Due now':`Due in ${x.days} day${x.days===1?'':'s'}`}</small></div><div class="item-amount">${money(x.amount)}</div></div>`).join(''):'Nothing due yet.';
 const segs=[['Mandatory',p.mandatory,'#ef4444'],['Living',p.essential,'#f59e0b'],['Goals',p.allocations.filter(a=>a.type==='Urgent goal').reduce((s,a)=>s+a.amount,0),'#8b5cf6'],['Debts',p.allocations.filter(a=>a.type==='Flexible debt').reduce((s,a)=>s+a.amount,0),'#3b82f6'],['Buffer',p.buffer,'#10b981'],['Free',p.free,'#94a3b8']];const total=Math.max(p.income,1);$('#flowBar').innerHTML=segs.filter(s=>s[1]>0).map(s=>`<span class="flow-seg" style="width:${Math.max(1,s[1]/total*100)}%;background:${s[2]}"></span>`).join('');$('#flowLegend').innerHTML=segs.filter(s=>s[1]>0).map(s=>`<span><i class="legend-dot" style="background:${s[2]}"></i>${s[0]} ${money(s[1])}</span>`).join('')}
function renderPlan(){const i=state.income;$('#fixedIncome').value=i.fixed||'';$('#sideIncome').value=i.side||'';$('#tradingIncome').value=i.trading||'';$('#otherIncome').value=i.other||'';$('#essentialBudget').value=i.essential||'';$('#bufferTarget').value=i.buffer||'';const p=buildPlan();let text;if(!p.income)text='Enter your monthly income, then add debts and goals. I’ll calculate what is non-negotiable and how to use the rest.';else if(p.shortfall>0)text=`Your current protected commitments are ${money(p.shortfall)} above available income. Fixed EMIs and essentials should be protected first. Reduce flexible debt payments, pause optional purchases, or add income before taking on new commitments.`;else{text=`You have ${money(p.income)} available this month. After protected commitments, essential living costs and your emergency buffer, ${money(p.free)} remains safe and flexible.`;const critical=p.goalPlans.find(g=>g.priority==='critical');if(critical)text+=` For ${critical.name}, reserve about ${money(critical.monthly)} per month to reach ${money(critical.need)} by ${critical.deadline}.`;}$('#planSummary').textContent=text;$('#allocationTable').innerHTML=p.allocations.length?`<table><thead><tr><th>Priority</th><th>Allocation</th><th>Type</th><th>Amount</th></tr></thead><tbody>${p.allocations.map((a,i)=>`<tr><td>${i+1}</td><td>${a.name}</td><td>${a.type}</td><td><strong>${money(a.amount)}</strong></td></tr>`).join('')}${p.free?`<tr><td>✓</td><td>Safe / flexible money</td><td>Available</td><td><strong>${money(p.free)}</strong></td></tr>`:''}</tbody></table>`:'No plan generated yet.'}
function renderTransactions(){const q=$('#txnSearch')?.value?.toLowerCase()||'', f=$('#txnTypeFilter')?.value||'all';let arr=[...state.transactions].sort((a,b)=>new Date(b.date)-new Date(a.date)).filter(t=>(f==='all'||t.type===f)&&(`${t.type} ${t.category} ${t.note}`.toLowerCase().includes(q)));$('#transactionList').innerHTML=arr.length?arr.map(t=>`<div class="list-item"><div class="item-main"><strong>${t.category||t.type}</strong><small>${t.type} • ${t.date}${t.note?` • ${t.note}`:''}</small></div><div class="item-amount">${t.type==='Expense'||t.type==='Debt Payment'?'-':'+'}${money(t.amount)}</div><button class="text-btn" onclick="removeItem('transactions','${t.id}')">Delete</button></div>`).join(''):'No transactions found.'}
function renderDebts(){const p=buildPlan();$('#debtCards').innerHTML=state.debts.length?state.debts.map(d=>{const alloc=p.allocations.find(a=>a.name===d.name&&(a.type==='Fixed debt'||a.type==='Flexible debt'));const pct=Math.min(100,Math.max(3,(+d.monthly/+d.balance)*100));return `<article class="mini-card"><span class="chip ${d.priority}">${d.fixed?'FIXED EMI':'FLEXIBLE'}</span><h3>${d.name}</h3><p>${d.type}${d.interest?` • ${d.rate}% interest`:''}</p><strong>${money(d.balance)} remaining</strong><div class="progress"><span style="width:${pct}%"></span></div><p>Normal payment: ${money(d.monthly)} • Assistant this month: <strong>${money(alloc?.amount||0)}</strong></p><div class="actions"><button onclick="recordDebtPayment('${d.id}')">Record payment</button><button class="remove" onclick="removeItem('debts','${d.id}')">Delete</button></div></article>`}).join(''):'<div class="empty-state">Add your loans, BNPL, friend/family debts and fixed EMIs.</div>'}
function renderGoals(){const p=buildPlan();$('#goalCards').innerHTML=state.goals.length?state.goals.map(g=>{const gp=p.goalPlans.find(x=>x.id===g.id),pct=Math.min(100,(+g.saved/+g.amount)*100);return `<article class="mini-card"><span class="chip ${g.priority}">${g.priority.toUpperCase()}</span><h3>${g.name}</h3><p>Deadline: ${g.deadline} • ${daysUntil(g.deadline)} days left</p><strong>${money(Math.max(0,+g.amount-+g.saved))} still needed</strong><div class="progress"><span style="width:${pct}%"></span></div><p>Recommended reservation: <strong>${money(gp?.monthly||0)} / month</strong></p><div class="actions"><button onclick="addGoalSaving('${g.id}')">Add saving</button><button class="remove" onclick="removeItem('goals','${g.id}')">Delete</button></div></article>`}).join(''):'<div class="empty-state">Add important requirements such as a course, visa fee, laptop, medical cost or family payment.</div>'}
function renderCredits(){const p=buildPlan();$('#creditCards').innerHTML=state.credits.length?state.credits.map(c=>{const room=Math.max(0,p.free);const normalNet=Math.max(0,+c.payment-(+c.reuse||0)-(+c.fee||0));let reuseRec=+c.reuse||0;if(room>+c.payment*.75)reuseRec=Math.max(0,(+c.reuse||0)-Math.min(+c.reuse||0,room*.5));const net=Math.max(0,+c.payment-reuseRec-(+c.fee||0));const months=net>0?Math.ceil(+c.balance/net):Infinity;const exit=reuseRec===0?'You can aim to stop reusing credit now.':`Recommended reuse this month: about ${money(reuseRec)}. As income improves, reduce reuse first.`;return `<article class="mini-card"><span class="chip ${reuseRec===0?'good':'high'}">${reuseRec===0?'EXIT MODE':'REVOLVING'}</span><h3>${c.name}</h3><strong>${money(c.balance)} outstanding</strong><p>Typical payment ${money(c.payment)} • monthly cost ${money(c.fee)} • typical reuse ${money(c.reuse)}</p><p>${exit}</p><p>At the recommended pattern, net balance reduction is about <strong>${money(net)}</strong> this month.${isFinite(months)?` Approx. ${months} month(s) to clear if maintained.`:''}</p><div class="actions"><button onclick="recordCreditPayment('${c.id}')">Record cycle</button><button class="remove" onclick="removeItem('credits','${c.id}')">Delete</button></div></article>`}).join(''):'<div class="empty-state">Add Tabby Card, a credit card or another account where you repay and reuse available credit.</div>'}
function renderAll(){renderDashboard();renderPlan();renderTransactions();renderDebts();renderGoals();renderCredits()}
window.removeItem=(kind,id)=>{if(!confirm('Delete this item?'))return;state[kind]=state[kind].filter(x=>x.id!==id);save();toast('Deleted')};
window.recordDebtPayment=id=>{const d=state.debts.find(x=>x.id===id);const v=Number(prompt(`Payment amount for ${d.name}:`,d.fixed?d.monthly:Math.min(d.monthly,d.balance)));if(!v)return;d.balance=Math.max(0,+d.balance-v);state.transactions.push({id:uid(),type:'Debt Payment',amount:v,category:d.name,date:new Date().toISOString().slice(0,10),note:'Debt repayment'});save();toast('Payment recorded')};
window.addGoalSaving=id=>{const g=state.goals.find(x=>x.id===id);const v=Number(prompt(`Amount saved for ${g.name}:`,0));if(!v)return;g.saved=Math.min(+g.amount,+g.saved+v);save();toast('Goal saving updated')};
window.recordCreditPayment=id=>{const c=state.credits.find(x=>x.id===id);const paid=Number(prompt(`Amount paid to ${c.name}:`,c.payment));if(!paid)return;const reused=Number(prompt('How much did you take/use back?',c.reuse||0))||0;c.balance=Math.max(0,+c.balance-paid+reused+(+c.fee||0));state.transactions.push({id:uid(),type:'Debt Payment',amount:paid,category:c.name,date:new Date().toISOString().slice(0,10),note:`Reused ${money(reused)}; fee ${money(c.fee)}`});save();toast('Credit cycle recorded')};
function openModal(name){$(`#${name}Modal`).classList.add('open')}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'))}
$$('.close').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));$('#quickAdd').onclick=()=>openModal('transaction');
$$('.nav-btn').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${v}-view`).classList.add('active');$('#pageTitle').textContent=b.innerText.trim();$('#sidebar').classList.remove('open')});$$('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`.nav-btn[data-view="${b.dataset.jump}"]`).click());$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$('#incomeForm').onsubmit=e=>{e.preventDefault();state.income={fixed:+$('#fixedIncome').value||0,side:+$('#sideIncome').value||0,trading:+$('#tradingIncome').value||0,other:+$('#otherIncome').value||0,essential:+$('#essentialBudget').value||0,buffer:+$('#bufferTarget').value||0};save();toast('Income and budget saved')};$('#generatePlanBtn').onclick=()=>{renderAll();toast('Money plan refreshed')};
$('#transactionForm').onsubmit=e=>{e.preventDefault();state.transactions.push({id:uid(),type:$('#txnType').value,amount:+$('#txnAmount').value,category:$('#txnCategory').value.trim(),date:$('#txnDate').value,note:$('#txnNote').value.trim()});e.target.reset();$('#txnDate').value=new Date().toISOString().slice(0,10);closeModals();save();toast('Transaction saved')};
$('#debtForm').onsubmit=e=>{e.preventDefault();state.debts.push({id:uid(),name:$('#debtName').value.trim(),type:$('#debtType').value,balance:+$('#debtBalance').value,fixed:$('#debtFixed').value==='yes',monthly:+$('#debtMonthly').value,dueDay:+$('#debtDueDay').value,interest:$('#debtInterest').value==='yes',rate:+$('#debtRate').value||0,priority:$('#debtPriority').value,minimum:+$('#debtMinimum').value||0});e.target.reset();closeModals();save();toast('Debt added')};
$('#goalForm').onsubmit=e=>{e.preventDefault();state.goals.push({id:uid(),name:$('#goalName').value.trim(),amount:+$('#goalAmount').value,deadline:$('#goalDeadline').value,priority:$('#goalPriority').value,saved:+$('#goalSaved').value||0,full:$('#goalFull').value==='yes'});e.target.reset();closeModals();save();toast('Urgent goal added')};
$('#creditForm').onsubmit=e=>{e.preventDefault();state.credits.push({id:uid(),name:$('#creditName').value.trim(),balance:+$('#creditBalance').value,payment:+$('#creditPayment').value,fee:+$('#creditFee').value||0,reuse:+$('#creditReuse').value||0,target:$('#creditTarget').value});e.target.reset();closeModals();save();toast('Revolving account added')};
$('#affordMethod').onchange=()=>{const custom=$('#affordMethod').value==='custom';$('#customMonthsWrap').classList.toggle('hidden',!custom);$('#customInterestWrap').classList.toggle('hidden',!custom)};
$('#affordForm').onsubmit=e=>{e.preventDefault();const p=buildPlan(),name=$('#affordName').value.trim(),cost=+$('#affordCost').value,method=$('#affordMethod').value;let months=1,total=cost,label='full payment';if(method==='pay4'){months=4;label='4 interest-free payments'}if(method==='custom'){months=Math.max(2,+$('#affordMonths').value||2);total=cost+(+$('#affordFee').value||0);label=`${months} installments`;}const monthly=total/months;const nowSafe=p.free;let status,title,detail;if(monthly<=Math.max(0,nowSafe*.65)&&p.shortfall===0){status='🟢 SAFE TO BUY';title=`Yes — ${name} fits your current plan.`;detail=`Your first payment would be ${money(monthly)} (${label}). You currently have about ${money(nowSafe)} safe/flexible money after protected commitments. After this payment, around ${money(Math.max(0,nowSafe-monthly))} remains. I would still keep future ${money(monthly)} payments reserved for the next ${months-1} month(s).`;}else if(monthly<=nowSafe&&p.shortfall===0){status='🟠 POSSIBLE, BUT TIGHT';title=`You can make the first payment, but ${name} would tighten your month.`;detail=`The payment is ${money(monthly)} and your safe/flexible money is ${money(nowSafe)}. That leaves only ${money(Math.max(0,nowSafe-monthly))}. Avoid this unless the purchase is important, and do not count future income until it arrives.`;}else{status='🔴 NOT RECOMMENDED YET';title=`The current plan does not safely support ${name}.`;detail=`The required payment is ${money(monthly)}, while your safe/flexible money is about ${money(nowSafe)}. You are short by roughly ${money(Math.max(0,monthly-nowSafe))} for this payment. Consider postponing, reducing the cost, or creating an urgent goal to save toward it.`;}$('#affordResult').innerHTML=`<strong>${status}</strong><h3 style="margin:8px 0">${title}</h3><p>${detail}</p><p><strong>Total commitment:</strong> ${money(total)} • <strong>Per payment:</strong> ${money(monthly)} • <strong>Payments:</strong> ${months}</p>`};
$('#txnSearch').oninput=renderTransactions;$('#txnTypeFilter').onchange=renderTransactions;
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fari-money-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...defaultState,...JSON.parse(r.result)};save();toast('Backup restored')}catch{alert('Invalid backup file')}};r.readAsText(f)};$('#resetBtn').onclick=()=>{if(confirm('This will permanently erase all local data. Continue?')){state=structuredClone(defaultState);save();toast('All data reset')}};
$('#txnDate').value=new Date().toISOString().slice(0,10);$('#goalDeadline').value=new Date(Date.now()+30*86400000).toISOString().slice(0,10);$('#todayText').textContent=new Date().toLocaleDateString('en-AE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderAll();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
